gg.jte.development-mode=true
gg.jte.template-suffix=.kte
spring.application.name=agent
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.ai.ollama.chat.model=gemma4:26b
#
spring.threads.virtual.enabled=true